sudo: required
dist: trusty
cache:
  directories:
    - node_modules
language: node_js
addons:
  chrome: stable
node_js:
 - "node"
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3
install:
 - npm install
after_script:
 - "sh -e /etc/init.d/xvfb stop"
